{% set version = "0.2.0" %}

package:
  name: jupyterlab-deck
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab-deck/jupyterlab_deck-{{ version }}.tar.gz
  sha256: f91eb4164538082718a3c7d4a605bf114eb7e034a199047a4098c18e0e8a25bc

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - flit-core >=3.9.0,<4
    - pip
    - python {{ python_min }}
  run:
    - jupyterlab >=3.5,<5.0.0a0
    - jupyterlab-fonts >=3.0.0
    - python >={{ python_min }}

test:
  imports:
    - jupyterlab_deck
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "jupyterlab-deck.*OK" labextensions
  requires:
    - jupyterlab
    - m2-grep  # [win]
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deathbeds/jupyterlab-deck
  summary: A lightweight presentation mode for JupyterLab.
  license: BSD-3-Clause
  doc_url: https://jupyterlab-deck.rtfd.io
  license_file:
    - LICENSE
    - src/_d/share/jupyter/labextensions/@deathbeds/jupyterlab-deck/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
