{% set version = "0.1.0" %}

package:
  name: jupyterlab-deck
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab-deck/jupyterlab-deck-{{ version }}.tar.gz
  sha256: 0115d5ee3106dff9408678fc6a7e9601e062ca0f611f01b752256a1942fd3f88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.7.1,<4
    - pip
    - python >=3.7
  run:
    - jupyterlab >=3.3,<4
    - jupyterlab-fonts >=2.1.1
    - python >=3.7

test:
  imports:
    - jupyterlab_deck
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "jupyterlab-deck.*OK" labextensions
  requires:
    - jupyterlab
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/deathbeds/jupyterlab-deck
  summary: A lightweight presentation mode for JupyterLab.
  license: BSD-3-Clause
  doc_url: https://jupyterlab-deck.rtfd.io
  license_file:
    - LICENSE
    - src/jupyterlab_deck/_d/share/jupyter/labextensions/@deathbeds/jupyterlab-deck/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
